### ISSUE TITLE
My Problem

### ISSUE THREAD

**Issue by Funkym77** [AndreyPavlenko/Fermata#78] opened 2021-11-19 12:18 UTC
hello andrey

please help me. I like your fermata program. but pegout 308 2020 worked once in my car, then it didn't work again. I couldn't figure out what is the problem. It worked once on my fermata 1.7.7 phone, android 10, android auto 6.9, with everything. then it didn't work. I see the fermata on the car screen. but it says "no new messages during this ride". What is the problem? can you help me? fermata 1.8.8, android autoda 7.0.614134 version when receiving this message.

**Comment by AndreyPavlenko** [comment] 2021-11-19 12:21
Please, see this issue https://github.com/AndreyPavlenko/Fermata/issues/77
Duplicate of #77

**Closed by AndreyPavlenko** 2021-11-19 12:21 UTC
