### ISSUE TITLE
Background Card behind the video file

### ISSUE THREAD

**Issue by italoboy** [AndreyPavlenko/Fermata#224] opened 2023-02-11 08:38 UTC
![IMG_20230210_160503](https://user-images.githubusercontent.com/61342502/218248848-961f828e-0a49-4279-af55-036f5dcd10e4.jpg)

Looks like it is not possible to remove?!

**Comment by AndreyPavlenko** [comment] 2023-02-11 11:11
Never seen such an issue. Is this card there only when playing video?

**Comment by italoboy** [comment] 2023-02-11 11:15
It is there when playing any video file. Not on my phone but on my car screen.

**Comment by italoboy** [comment] 2023-02-11 11:58
It is music player (card) of coolwalk, how to fix this?!

**Comment by italoboy** [comment] 2023-02-17 08:39
Any update to fix this ?;

**Comment by AndreyPavlenko** [comment] 2023-02-17 12:41
No updates. Unfortunately, I can't reproduce. Have you tried a different device, do you have the same issue?

**Comment by italoboy** [comment] 2023-02-17 12:51
> No updates. Unfortunately, I can't reproduce. Have you tried a different device, do you have the same issue?

I've tried anything, this happens in coolwalk.

**Comment by AndreyPavlenko** [comment] 2023-03-15 16:47
Fixed in 1.9.1.

**Closed by AndreyPavlenko** 2023-03-15 16:47 UTC

**Comment by italoboy** [comment] 2023-03-15 16:50
> Fixed in 1.9.1.

Great, tnx for fixing.
