### ISSUE TITLE
Fermata auto not working last update

### ISSUE THREAD

**Issue by Fla75** [AndreyPavlenko/Fermata#96] opened 2021-12-04 13:37 UTC
hello everyone ... even for me after the last update stop auto no longer appears on android auto you only see fermata control .... solutions?
![Screenshot_20211204-143041_Android Auto](https://user-images.githubusercontent.com/95533370/144711517-af1798c5-b11d-4dc3-b495-dc6bf45f1fcc.jpg)

**Comment by AndreyPavlenko** [comment] 2021-12-04 13:39
Duplicate of #92

**Closed by AndreyPavlenko** 2021-12-04 13:39 UTC
