### ISSUE TITLE
Fermata Auto 1.9.6 not working with OneUi 6 Android 14

### ISSUE THREAD

**Issue by kimjungho27** [AndreyPavlenko/Fermata#342] opened 2023-12-28 00:34 UTC
Fermata Auto 1.9.6 not even showing anymore on the Android Auto app. Android 14, Samsung Galaxy S23+ OneUI 6. Android Auto is on developer mode but Fermata Auto stopped showing. Removed it, cleared cache, re installed it. Nothing

Please help me..

**Comment by trebory6** [comment] 2023-12-29 03:16
I am having the same exact issue.

Updated to One UI 6 yesterday and Fermata started glitching out and ended up disappearing from the android auto app list.

**Comment by maripic69** [comment] 2023-12-29 12:41
И при мен изчезна!чакаме решение¡!!!

**Comment by kr4bs28** [comment] 2023-12-29 19:30
same here, solution yet?

**Comment by YoavSl** [comment] 2024-01-01 10:25
Same here, S22 Ultra OneUI 6
Please help

**Comment by nino-a11y** [comment] 2024-01-02 08:27
Same also, it worked fine even on Android 14, then i updated fermata from 1.9.5 to 1.9.6 from there android auto no more recognize it sadly.
I did everything to figure it out, maybe android auto need to be patched like YouTube revanced
Thank you pav

**Comment by jwkyeongzz** [comment] 2024-01-02 09:13
same here. Z fold5 OneUI 6

**Comment by fork04** [comment] 2024-01-02 10:39
Same here, Samsung S23+ OneUI 6

**Comment by agentmyke** [comment] 2024-01-02 21:15
Same here after updating to New Version, the app icon is gone on My S23 Ultra  Android app list are u going to remake another Version to fix it?  Thx

**Comment by JVKeller** [comment] 2024-01-03 23:06
Same here. S23 ultra. I have this set up in Android studio, if I get time I'll see if I can debug at all.

**Comment by agentmyke** [comment] 2024-01-03 23:09
Now i can use with aawireless with developer Mode activated 🤞

**Comment by nino-a11y** [comment] 2024-01-04 04:45
> Now i can use with aawireless with developer Mode activated 🤞

How did you do it ?

**Comment by JVKeller** [comment] 2024-01-04 14:09
I can't see that making a difference. Developer mode should have been enabled before Fermata even had the chance to update. I have/had it enabled and updated, and it broke.

Tried reinstalling with AAStore but it's got an older version so that was no help either. 

Which package manager are you guys installing it with?

**Comment by Namaisape** [comment] 2024-01-10 12:14
Trovato soluzioni per chi ha aggiornato ad Android 14? Qualcuno ha apk di TV SnartTv?

**Comment by JVKeller** [comment] 2024-01-11 13:32
I set up the desktop-head-unit.exe app and tried it there and it showed up, but it doesn't show up with wireless AA in the car. I didn't try without the wireless, I'll try that later.

**Comment by Polonium2100** [comment] 2024-01-11 18:31
Same here after one ui 6

**Comment by maripic69** [comment] 2024-01-11 19:39
Това работи ли на андроид 14

**Comment by JVKeller** [comment] 2024-01-15 18:13
Still an issue not showing up. It's listed in the installed apps, works with test headunit, but in the car the app doesn't show.

![image](https://github.com/AndreyPavlenko/Fermata/assets/29125090/29fd14f2-8358-4cd8-8174-7f75b6a21c48)

**Comment by JVKeller** [comment] 2024-01-15 18:19
Lots of threads for this:

[https://github.com/AndreyPavlenko/Fermata/issues/327](https://github.com/AndreyPavlenko/Fermata/issues/327)

**Comment by AndreyPavlenko** [comment] 2024-01-26 18:32
Closing as duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327

**Closed by AndreyPavlenko** 2024-01-26 18:32 UTC
