### ISSUE TITLE
1.9.7

### ISSUE THREAD

**Issue by TalSivan** [AndreyPavlenko/Fermata#354] opened 2024-01-10 21:07 UTC
FERMATA AUTO back to work in android auto ??

**Comment by AndreyPavlenko** [comment] 2024-01-10 21:08
If you mean Android 14, then no.

**Comment by TalSivan** [comment] 2024-01-10 21:13
> If you mean Android 14, then no.

When is it ?

**Comment by AndreyPavlenko** [comment] 2024-01-10 21:18
Unfortunately, I don't know.

**Comment by vegetaleb** [comment] 2024-01-11 11:09
It won't work even with root?

**Comment by AndreyPavlenko** [comment] 2024-01-11 13:03
I've not tested, but probably it works. If you have Magisk, try this - https://github.com/AndreyPavlenko/Fermata/discussions/122#discussioncomment-4307775 .

**Comment by vegetaleb** [comment] 2024-01-11 13:25
> I've not tested, but probably it works. If you have Magisk, try this - [#122 (comment)](https://github.com/AndreyPavlenko/Fermata/discussions/122#discussioncomment-4307775) .

This what I did but no joy, only Fermata Control is showing in AA

**Comment by AndreyPavlenko** [comment] 2024-01-11 13:30
Have you checked LSPosed logs? Is the Fermata Auto module loaded?

**Comment by vegetaleb** [comment] 2024-01-11 13:46
> Have you checked LSPosed logs? Is the Fermata Auto module loaded?

[LSPosed_2024-01-11T15_44_57.115457.zip](https://github.com/AndreyPavlenko/Fermata/files/13903980/LSPosed_2024-01-11T15_44_57.115457.zip)
Yes enabled, attached the logs

**Comment by AndreyPavlenko** [comment] 2024-01-11 13:54
Seems, the module is loaded:
I/LSPosed-Bridge  ]   Loading class me.aap.fermata.auto.Xposed

**Comment by vegetaleb** [comment] 2024-01-11 14:01
> Seems, the module is loaded: I/LSPosed-Bridge ] Loading class me.aap.fermata.auto.Xposed

Yes but not showing in AA

**Comment by vegetaleb** [comment] 2024-01-11 15:00
Finally showing after updating AA to version 11!

**Comment by scheuerer** [comment] 2024-01-12 09:26
But this only works with "rooted" phones, I'm right?

**Comment by AndreyPavlenko** [comment] 2024-01-12 12:29
Right.

**Comment by princepeace** [comment] 2024-01-12 14:43
I thought that it also works if you use AAWireless, and put it in developer mode?

**Comment by AndreyPavlenko** [comment] 2024-01-12 23:48
Yes, it works with AAWireless without root.

**Comment by Goyena** [comment] 2024-01-13 15:57
1.9.7 works perfectly for me. Yeah, Fermata is back!
- Fermata Auto shows in AA customize launcher on phone
- Fermata Mirror and Fermata Auto show on car
- mirroring is more stable than Screen2Auto for me
- Poco F3 (vanilla, never rooted) MIUI 14.0.9
- installed via KingInstaller. 

Is it really mirroring? I can use my phone and Fermata at the same time. I can even watch a different videos on the Fermata.phone app, and the Fermata on the car screen simultaneously. 

I saw the ChatGPT add-on: is there anyway you could include the continuous voice conversation the OpenAI app now has (tap on the headphone icon) in the mirroring? (but via normal Google login, not api key) I'd love to be able to drive down the road chatting with it. The pulsating blob would look sort of like KITT (from Knight Rider).

**Comment by AndreyPavlenko** [comment] 2024-01-13 18:07
> Is it really mirroring? I can use my phone and Fermata at the same time. I can even watch a different videos on the Fermata.phone app, and the Fermata on the car screen simultaneously.

You can do this with fermata app, but not the mirror app. The mirror app mirrors the entire phone screen.

**Comment by AXIOM-JH** [comment] 2024-01-15 15:42
@AndreyPavlenko I'm struggling to get Fermata to work correctly with my new phone (ThinkPhone by Lenovo, Android 13). Had a Samsung Galaxy S20+ (Android 13) working just fine before. Everything appears to install correctly but will not display video from the head unit. Any advice would be appreciated. 
*Note - The Samsung Galaxy S20+ was using 1.9.1, no issues.

**Comment by AndreyPavlenko** [comment] 2024-01-26 18:29
Closing as duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327

**Closed by AndreyPavlenko** 2024-01-26 18:29 UTC
