### ISSUE TITLE
FERMATA AUTO NOT WORKING ON ANDROID 12

### ISSUE THREAD

**Issue by madala1819** [AndreyPavlenko/Fermata#128] opened 2022-01-25 02:05 UTC
Hey haii ...my fermata auto is not showing up in android auto after upgrading to android 12 ...tried to reinstall the app with newer versions but there is no use of it ....could anyone please help me with this...thank you in advance

**Comment by FastenM** [comment] 2022-01-25 06:30
Downgrade android auto to version 6.9.613744
(Available at apkmirror.com)

**Comment by AndreyPavlenko** [comment] 2022-01-25 10:32
Duplicate of #121

**Closed by AndreyPavlenko** 2022-01-25 10:32 UTC
