### ISSUE TITLE
Keeps crashing since one UI 4.0 update

### ISSUE THREAD

**Issue by Digilydeez** [AndreyPavlenko/Fermata#115] opened 2021-12-27 21:22 UTC
Fermata auto keeps crashing since I did the samsung one UI 4.0 update on my phone. I can run the app on my phone no problem but when I plug it in my car it wont even open. What can I do to fix that?

**Comment by AndreyPavlenko** [comment] 2021-12-27 21:25
Have you updated to Android 12? The only solution - downgrade AA to 6.9.

**Comment by Digilydeez** [comment] 2021-12-27 22:46
It worked thank you!

**Comment by AndreyPavlenko** [comment] 2021-12-27 22:47
Duplicate of #113

**Closed by AndreyPavlenko** 2021-12-27 22:47 UTC
