### ISSUE TITLE
Lost FERMATA AUTO icon in AA

### ISSUE THREAD

**Issue by PasqualeEsposito78** [AndreyPavlenko/Fermata#95] opened 2021-12-04 10:38 UTC
Hi after one day that I installed FERMATA AUTO (controller  and player) I'm not able to found in the AA display the player icon. It is available only the controller icon. I have installed F.A. 1.8.9 and my AA version is 1.2  with Android 10. Please can you help me?

**Comment by PasqualeEsposito78** [comment] 2021-12-04 10:40
![Screenshot_20211204-113928](https://user-images.githubusercontent.com/95527141/144706517-b8dbe1c7-f4db-44b5-8da2-365780fb6759.png)
Here you can see that I lost app/icon of the FA player

**Comment by Carlos1988rm** [comment] 2021-12-04 10:51
Ha desaparecido todo fermata, screen2auto...

**Comment by Alejandro2454** [comment] 2021-12-04 13:11
Desapareció todo, solo queda fermata control. Tengo AA 7.0, android 11. NO
ROOT

**Comment by AndreyPavlenko** [comment] 2021-12-04 13:41
Duplicate of #92

**Closed by AndreyPavlenko** 2021-12-04 13:41 UTC
