### ISSUE TITLE
Fermata Auto 1.9.7 not working with OneUi 6 Android 14

### ISSUE THREAD

**Issue by kimjungho27** [AndreyPavlenko/Fermata#358] opened 2024-01-12 06:30 UTC
Hello .

Does the new Permata Auto 1.9.7 work on OneUi 6 Android 14??

I'm still not working with OneUi 6 Android 14

Please tell me how to do it.

Thanks

**Comment by NICOVRR** [comment] 2024-01-12 12:32
same problem with new version Android xiaomi 13 pro

**Comment by abdo1991yogi** [comment] 2024-01-12 15:28
Galaxy s22 ultra dont work
![Uploading Screenshot_٢٠٢٤٠١١٢_١٨٢٧١٧_Settings.jpg…]()

**Comment by maripic69** [comment] 2024-01-13 07:31
Мислех ,че тази версия работи с Android14 ONE UI 6 но и тя не се показва в Android Auto!

**Comment by abdo1991yogi** [comment] 2024-01-13 07:37
Yes, this is what happens, so what do I do?

في السبت، ١٣ كانون الثاني ٢٠٢٤، ١٠:٣١ ص maripic69 ***@***.***>
كتب:

**Comment by robertj2000** [comment] 2024-01-13 15:55
In reviewing the other issues previously posted, I understand this is caused by additional security protocols recently introduced with Android 14. Furthermore, the developer has stated he's still trying to find a solution. 

In the meantime, I have a question for the community. Has anyone successfully downgraded/reverted to Android 13? I have a Samsung S23 Ultra and I'm going to try this. If anyone has some tips, links, or warnings, please share. Thank you.

**Comment by adigial** [comment] 2024-01-14 07:35
> In reviewing the other issues previously posted, I understand this is caused by additional security protocols recently introduced with Android 14. Furthermore, the developer has stated he's still trying to find a solution.
> 
> In the meantime, I have a question for the community. Has anyone successfully downgraded/reverted to Android 13? I have a Samsung S23 Ultra and I'm going to try this. If anyone has some tips, links, or warnings, please share. Thank you.

https://github.com/AndreyPavlenko/Fermata/issues/335 took me almost a day of researching how to do it but I was able to roll back no problem.  I followed a youtube guide and then used some intuition to flash the alphabet files.

**Comment by Francois110751230** [comment] 2024-01-15 20:36
Dear mister,

Can you help me please with fermata working on android 14. Samsung galaxy s23fe

**Comment by AndreyPavlenko** [comment] 2024-01-15 23:32
The easiest solution is to buy this device - https://www.aawireless.io .

**Comment by iiD4x** [comment] 2024-01-17 09:56
> The easiest solution is to buy this device - https://www.aawireless.io .

Alright, what makes it usable if i have AAWireless ? is there anything i need to set on AAWireless app ?

**Comment by AndreyPavlenko** [comment] 2024-01-17 12:39
> Alright, what makes it usable if i have AAWireless ? is there anything i need to set on AAWireless app ?

You need to enable the developer mode. It's confirmed to work by many users.

**Comment by ace2927** [comment] 2024-01-19 01:33
For a temporary solution Screen2auto still works on oneui6 Android 14. Thank you Developers for taking ya time to coding...

**Comment by theonlyderpderp** [comment] 2024-01-22 15:27
> May someone clarify what AAWireless in developer mode does? I have the combination, however Fermata Auto still doesn't work. Is there some other functionality you gain?

Never mind, found the solution in another thread. Fermata Auto now shows up in Android Auto, however, crashes when I try to launch it.

**Comment by Cinemacloud** [comment] 2024-01-22 21:37
> > May someone clarify what AAWireless in developer mode does? I have the combination, however Fermata Auto still doesn't work. Is there some other functionality you gain?
> 
> Never mind, found the solution in another thread. Fermata Auto now shows up in Android Auto, however, crashes when I try to launch it.

Can you point me to how to get this far?

**Comment by theonlyderpderp** [comment] 2024-01-23 03:18
> > > May someone clarify what AAWireless in developer mode does? I have the combination, however Fermata Auto still doesn't work. Is there some other functionality you gain?
> > 
> > 
> > Never mind, found the solution in another thread. Fermata Auto now shows up in Android Auto, however, crashes when I try to launch it.
> 
> Can you point me to how to get this far?

Open the AAWireless app and connect to your device. In the top right is a gear icon. There you will be able to access developer mode.

**Comment by tkotam** [comment] 2024-01-24 09:44
> For a temporary solution Screen2auto still works on oneui6 Android 14. Thank you Developers for taking ya time to coding...

Is this in AA wireless or Wired?

**Comment by maripic69** [comment] 2024-01-25 02:30
> > Най-лесното решение е да закупите това устройство - https://www.aawireless.io .
> 
> Добре, какво го прави използваем, ако имам AAWireless? Има ли нещо, което трябва да задам на приложението AAWireless?



> Най-лесното решение е да закупите това устройство - https://www.aawireless.io .

Ок ама аз и сега се връзвам с АА без кабел!!Това устройство как се връзва към автомобила!?

**Comment by ace2927** [comment] 2024-01-25 02:46
> > For a temporary solution Screen2auto still works on oneui6 Android 14. Thank you Developers for taking ya time to coding...
> 
> Is this in AA wireless or Wired?
Not on AA wireless on my S23 Ultra

**Comment by tkotam** [comment] 2024-01-25 05:07
> > > For a temporary solution Screen2auto still works on oneui6 Android 14. Thank you Developers for taking ya time to coding...
> > 
> > 
> > Is this in AA wireless or Wired?
> > Not on AA wireless on my S23 Ultra

Can't seem to get it to work on an S23 Ultra as well using wired.

**Comment by ace2927** [comment] 2024-01-25 21:28
> > > > For a temporary solution Screen2auto still works on oneui6 Android 14. Thank you Developers for taking ya time to coding...
> > > 
> > > 
> > > Is this in AA wireless or Wired?
> > > Not on AA wireless on my S23 Ultra
> 
> Can't seem to get it to work on an S23 Ultra as well using wired.

Makesure to turn off open on start in the settings launcher of the app. Did you download the app through (AAAD)

**Comment by tkotam** [comment] 2024-01-26 12:24
> > > > > For a temporary solution Screen2auto still works on oneui6 Android 14. Thank you Developers for taking ya time to coding...
> > > > 
> > > > 
> > > > Is this in AA wireless or Wired?
> > > > Not on AA wireless on my S23 Ultra
> > 
> > 
> > Can't seem to get it to work on an S23 Ultra as well using wired.
> 
> Makesure to turn off open on start in the settings launcher of the app. Did you download the app through (AAAD)

I can't even make Screen2auto to show up in android auto. Tried installing using both king installer and AAAD. I am uprooted, BTW. Could that be the issue? 

S23 Ultra on Android 14

**Comment by tkotam** [comment] 2024-01-26 12:38
> > > > > > For a temporary solution Screen2auto still works on oneui6 Android 14. Thank you Developers for taking ya time to coding...
> > > > > 
> > > > > 
> > > > > Is this in AA wireless or Wired?
> > > > > Not on AA wireless on my S23 Ultra
> > > 
> > > 
> > > Can't seem to get it to work on an S23 Ultra as well using wired.
> > 
> > 
> > Makesure to turn off open on start in the settings launcher of the app. Did you download the app through (AAAD)
> 
> I can't even make Screen2auto to show up in android auto. Tried installing using both king installer and AAAD. I am uprooted, BTW. Could that be the issue?
> 
> S23 Ultra on Android 14

One more thing. 
1) For Screen2auto, I tried both with Android Auto Developer mode enabled and disabled. Still the same. The icon won't show in Android Auto
2) For Fermata, with Developer mode on, I am at least able to get Fermata Control on Android Auto.

**Comment by AndreyPavlenko** [comment] 2024-01-26 12:47
> 2\. For Fermata, with Developer mode on, I am at least able to get Fermata Control on Android Auto.

Have you installed it with KingInstaller?

**Comment by tkotam** [comment] 2024-01-26 16:06
> > 2. For Fermata, with Developer mode on, I am at least able to get Fermata Control on Android Auto.
> 
> Have you installed it with KingInstaller?

Retried Fermata installation using King Installer and AAAD. Again android auto in dev mode. Fermata Control shows up in android auto but no Fermata Auto icon for both AAAD and King. No bacon. :-D

**Comment by AndreyPavlenko** [comment] 2024-01-26 18:31
Sorry, I thought you are talking about the dev mode in AAWireless. The AA dev mode does not help here.

**Comment by AndreyPavlenko** [comment] 2024-01-26 18:32
Closing as duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327

**Closed by AndreyPavlenko** 2024-01-26 18:32 UTC
