### ISSUE TITLE
IPTV cannot load chanel

### ISSUE THREAD

**Issue by ahhl** [AndreyPavlenko/Fermata#127] opened 2022-01-23 10:49 UTC
i am using github iptv m3u. previously once key-in the link, fermata will load all the channel
now, it cant load any. the link now shows empty even for the previous setting. i have tested the m3u link on PC and on PC the link still works

**Comment by AndreyPavlenko** [comment] 2022-01-23 20:24
Duplicate of #125

**Comment by AndreyPavlenko** [comment] 2022-01-23 20:27
The issue has been fixed, but the fix is not released yet. Please, ask the playlist owner to remove the empty x-tvg-url="" tag from the playlist.

**Comment by FastenM** [comment] 2022-01-25 01:08
I have a different issue with the same iptv from github

I add a few channels to the favorites list, and some time later i come back fo the favorites tab and the channels are different of what i originally saved.

**Comment by AndreyPavlenko** [comment] 2022-01-25 11:05
@FastenM In favorites the channel sequence number is saved, not the name. If the playlist is changed and you have a different channel on that position, you will have a different channel in favorites. Perhaps, the implementation should be changed to operate channel names, instead of seq nums, but it's also not reliable, because the name can be changed too.

**Closed** 2024-01-10 00:19 UTC
