### ISSUE TITLE
New 1.9.7 update doesnt mirror in car 

### ISSUE THREAD

**Issue by Pb12pb** [AndreyPavlenko/Fermata#404] opened 2024-02-24 02:06 UTC
Having issues with the update and it no longer screen plays youtube in car. I have an Samsung s23 ultra.

**Comment by AndreyPavlenko** [comment] 2024-02-24 12:51
Duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327

**Closed by AndreyPavlenko** 2024-02-24 12:51 UTC
