### ISSUE TITLE
IPTV m3u playlist not loading

### ISSUE THREAD

**Issue by Yamilcfg** [AndreyPavlenko/Fermata#194] opened 2022-09-12 13:47 UTC
Hello,

I have an IPTV m3u playlist and it won't load using the TV addon. When I add the m3u playlist I get 0 channels and 0 groups. What I'm doing wrong? any specific suggestions?? Thanks in advance

**Comment by AndreyPavlenko** [comment] 2022-09-12 14:50
Duplicate of #196

**Closed by AndreyPavlenko** 2022-09-12 14:50 UTC
