### ISSUE TITLE
Fermata Auto 1.9.7 does not work on my Pixel 6a with Android 14

### ISSUE THREAD

**Issue by pelado66** [AndreyPavlenko/Fermata#365] opened 2024-01-21 02:02 UTC
I installed fermata auto 1.9.7 with kingstaller 1.4 with all permissions and the icon does not appear in AA. I have pixel 6a with A14. I've tried everything I can and nothing. Any ideas?

**Comment by Gullzway** [comment] 2024-01-23 20:49
You'll have to root the phone.

Install Magisk
Magisk => Settings => Magisk => Check Zygisk
Install LSPosed (Zygisk) + Shamiko
Install the Android-Auto-XLauncher-Unlocked app with KingInstaller
LSPosed => Modules => Check Enable module + Check Android Auto
Reboot

Install Fermata with KingInstaller

**Comment by Saicopate** [comment] 2024-01-25 23:53
So Fermata Auto is only on rooted devices now?

**Comment by AndreyPavlenko** [comment] 2024-01-25 23:56
For non rooted you may use AAwireless. For more details - https://github.com/AndreyPavlenko/Fermata/issues/327.

**Comment by AndreyPavlenko** [comment] 2024-01-26 18:29
Closing as duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327

**Closed** 2024-01-26 18:29 UTC
