### ISSUE TITLE
Channels constantly change independently

### ISSUE THREAD

**Issue by PoPeYe2000** [AndreyPavlenko/Fermata#257] opened 2023-05-07 10:44 UTC
[DE-M3u-List-4-07-05-2023.zip](https://github.com/AndreyPavlenko/Fermata/files/11414798/DE-M3u-List-4-07-05-2023.zip)
 ##
/Hello, no matter which M3u list I use, the channels change independently. It's as if someone is switching. I have already checked that the Internet connection is not the problem.
I'm attaching the M3u list here, so maybe you can understand it.
What could be the reason for this? Is there a setting for it somewhere in the menu?

**Comment by AndreyPavlenko** [comment] 2023-05-07 16:09
The channels are switching when either reaching end of stream or the playback failed. I tested the attached playlist on the desktop version of VLC and MPV and the behavior is the same. Here is the second URL from the playlist (Das Erste HD):
```
mpv http://kardessa.xyz:8080/Eftiykusi/4wPhYsVEYqru/2331
 (+) Video --vid=1 (h264 1280x720 50.000fps)
 (+) Audio --aid=1 --alang=deu (aac 2ch 44100Hz)
     Audio --aid=2 --alang=deu (aac 2ch 44100Hz)
     Audio --aid=3 --alang=deu (aac 2ch 44100Hz)
     Audio --aid=4 --alang=deu (aac 2ch 44100Hz)
[ffmpeg] AVHWDeviceContext: cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Using hardware decoding (vaapi-copy).
AO: [pipewire] 44100Hz stereo 2ch floatp
VO: [gpu] 1280x720 nv12
AV: 00:00:00 / 00:00:01 (56%) A-V:  0.001 Dropped: 11 Cache: 0.3s/192KB
[ffmpeg] http: Stream ends prematurely at 626296, should be 18446744073709551615
AV: 00:00:01 / 00:00:01 (98%) A-V:  0.000 Dropped: 23 Cache: 0.0s

Exiting... (End of file)
```

**Comment by PoPeYe2000** [comment] 2023-05-07 18:42
I don't quite understand. Is the problem with the M3u file? Or what can I do to make it work?

**Comment by AndreyPavlenko** [comment] 2023-05-07 20:48
The problem is not in the M3U file. The file is ok, this is just a text file. I opened the file in a text editor, copied the second URL and tried to play it in MPV. After 1 second playback, the stream closed by the server. For some reason, the server drops the connection. Have you tested this playlist with any other player?

**Comment by AndreyPavlenko** [comment] 2023-05-08 19:30
I'm talkin not About Fermata Auto. Install any other iptv player to your phone and check if this playlist works.

**Comment by AndreyPavlenko** [comment] 2023-05-08 23:39
The server closes connection in about a second. Fermata decides that the track ended, automatically switches to the next. Televizio, seems, reopen it again and again ... and it works, however, very unstable. Sometimes short episodes are missing, sometimes - repeated.

**Comment by PoPeYe2000** [comment] 2023-05-09 17:20
But if it's not the M3u file, what is it? I've had M3u files that worked before. But I'm not sure if they were http files or text files. In Fermata Auto everything works except the option to use an M3u file. I don't know what to do.

**Comment by AndreyPavlenko** [comment] 2023-05-09 17:59
This is M3U file and it's valid. You can open it in any text editor. The file contains links to the streams. This is one of the links from this file - http://kardessa.xyz:8080/Eftiykusi/4wPhYsVEYqru/2331. When playing this stream, the playback interrupts in a few seconds because the server drops the connection.
Btw, now I'm getting `401 Unauthorized` error, when trying to play this stream. Televizo does not work either.

**Closed** 2023-07-10 22:40 UTC
