### ISSUE TITLE
Hi, does this help with android 14?

### ISSUE THREAD

**Issue by Majeed91** [AndreyPavlenko/Fermata#345] opened 2024-01-03 14:04 UTC
https://github.com/AndreyPavlenko/Fermata/discussions/315#discussioncomment-7663582

**Comment by AndreyPavlenko** [comment] 2024-01-03 22:08
No, it doesn't.

**Comment by AndreyPavlenko** [comment] 2024-01-12 23:41
https://github.com/AndreyPavlenko/Fermata/issues/327#issuecomment-1890143200

**Comment by AndreyPavlenko** [comment] 2024-01-26 18:30
Closing as duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327

**Closed by AndreyPavlenko** 2024-01-26 18:30 UTC
